#include "HookManager.h"
#include <algorithm>
#include <cmath>
#include <iostream>

namespace MacroK {

HookManager* HookManager::s_instance = nullptr;

HookManager::HookManager() {
    s_instance = this;
}

HookManager::~HookManager() {
    shutdown();
    if (s_instance == this) {
        s_instance = nullptr;
    }
}

bool HookManager::init() {
    if (m_initialized.load()) return true;

    std::atomic<bool> ready{false};
    m_hookThread = std::thread([this, &ready]() {
        this->hookThreadFunc(ready);
    });

    while (!ready.load()) {
        std::this_thread::yield();
    }

    return m_initialized.load();
}

void HookManager::shutdown() {
    stopRecording();

    if (!m_initialized.load()) return;
    m_initialized.store(false);

    if (m_hookThreadId != 0) {
        PostThreadMessage(m_hookThreadId, WM_QUIT, 0, 0);
    }

    if (m_hookThread.joinable()) {
        m_hookThread.join();
    }

    m_hookThreadId = 0;
}

void HookManager::hookThreadFunc(std::atomic<bool>& ready) {
    m_hookThreadId = GetCurrentThreadId();
    HINSTANCE hInst = GetModuleHandle(nullptr);

    m_mouseHook = SetWindowsHookEx(WH_MOUSE_LL, LowLevelMouseProc, hInst, 0);
    m_keyboardHook = SetWindowsHookEx(WH_KEYBOARD_LL, LowLevelKeyboardProc, hInst, 0);

    if (!m_mouseHook || !m_keyboardHook) {
        if (m_mouseHook) UnhookWindowsHookEx(m_mouseHook);
        if (m_keyboardHook) UnhookWindowsHookEx(m_keyboardHook);
        m_mouseHook = nullptr;
        m_keyboardHook = nullptr;
        m_initialized.store(false);
        ready.store(true);
        return;
    }

    m_initialized.store(true);
    ready.store(true);

    MSG msg;
    while (GetMessage(&msg, nullptr, 0, 0) > 0) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    if (m_mouseHook) {
        UnhookWindowsHookEx(m_mouseHook);
        m_mouseHook = nullptr;
    }
    if (m_keyboardHook) {
        UnhookWindowsHookEx(m_keyboardHook);
        m_keyboardHook = nullptr;
    }
}

void HookManager::addIgnoredKey(uint32_t vkCode) {
    std::lock_guard<std::mutex> lock(m_ignoredKeysMutex);
    if (std::find(m_ignoredKeys.begin(), m_ignoredKeys.end(), vkCode) == m_ignoredKeys.end()) {
        m_ignoredKeys.push_back(vkCode);
    }
}

void HookManager::setIgnoredKeys(const std::vector<uint32_t>& keys) {
    std::lock_guard<std::mutex> lock(m_ignoredKeysMutex);
    m_ignoredKeys = keys;
}

void HookManager::clearIgnoredKeys() {
    std::lock_guard<std::mutex> lock(m_ignoredKeysMutex);
    m_ignoredKeys.clear();
}

bool HookManager::startRecording(const MacroSettings& settings) {
    if (!m_initialized.load()) {
        if (!init()) return false;
    }

    if (m_isRecording.load()) return false;

    m_settings = settings;
    clearEvents();

    // Query current cursor position so initial stationary state is not recorded as a move!
    POINT curPos;
    if (GetCursorPos(&curPos)) {
        m_lastRecordedX = curPos.x;
        m_lastRecordedY = curPos.y;
    } else {
        m_lastRecordedX = -1;
        m_lastRecordedY = -1;
    }

    m_lastEventTimeMs = 0;
    m_lastMouseMoveTimeMs = 0;

    m_timer.start();
    m_isRecording.store(true);
    return true;
}

void HookManager::stopRecording() {
    m_isRecording.store(false);
}

const std::vector<MacroEvent>& HookManager::getRecordedEvents() const {
    std::lock_guard<std::mutex> lock(m_eventMutex);
    return m_events;
}

void HookManager::setRecordedEvents(const std::vector<MacroEvent>& events) {
    std::lock_guard<std::mutex> lock(m_eventMutex);
    m_events = events;
}

bool HookManager::removeEvent(size_t index) {
    std::lock_guard<std::mutex> lock(m_eventMutex);
    if (index >= m_events.size()) return false;
    if (index + 1 < m_events.size()) {
        m_events[index + 1].delayMs += m_events[index].delayMs;
    }
    m_events.erase(m_events.begin() + index);
    return true;
}

bool HookManager::removeEvents(std::vector<size_t> indices) {
    std::lock_guard<std::mutex> lock(m_eventMutex);
    if (indices.empty() || m_events.empty()) return false;

    // Sort descending to safely erase from back to front
    std::sort(indices.begin(), indices.end(), std::greater<size_t>());
    indices.erase(std::unique(indices.begin(), indices.end()), indices.end());

    for (size_t idx : indices) {
        if (idx < m_events.size()) {
            if (idx + 1 < m_events.size()) {
                m_events[idx + 1].delayMs += m_events[idx].delayMs;
            }
            m_events.erase(m_events.begin() + idx);
        }
    }
    return true;
}

void HookManager::clearEvents() {
    std::lock_guard<std::mutex> lock(m_eventMutex);
    m_events.clear();
}

LRESULT CALLBACK HookManager::LowLevelMouseProc(int nCode, WPARAM wParam, LPARAM lParam) {
    if (nCode >= 0 && s_instance && s_instance->m_isRecording.load()) {
        const MSLLHOOKSTRUCT* pMouse = reinterpret_cast<const MSLLHOOKSTRUCT*>(lParam);
        // Ignore synthetic events generated by SendInput
        if (!(pMouse->flags & LLMHF_INJECTED)) {
            s_instance->handleMouseEvent(wParam, pMouse);
        }
    }
    return CallNextHookEx(nullptr, nCode, wParam, lParam);
}

LRESULT CALLBACK HookManager::LowLevelKeyboardProc(int nCode, WPARAM wParam, LPARAM lParam) {
    if (nCode >= 0 && s_instance) {
        const KBDLLHOOKSTRUCT* pKey = reinterpret_cast<const KBDLLHOOKSTRUCT*>(lParam);

        // Global hotkey detection (even when not recording)
        if (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN) {
            if (!(pKey->flags & LLKHF_INJECTED) && s_instance->m_hotkeyCallback) {
                s_instance->m_hotkeyCallback(pKey->vkCode);
            }
        }

        // If recording, store the keyboard event
        if (s_instance->m_isRecording.load()) {
            bool isIgnored = false;
            {
                std::lock_guard<std::mutex> lock(s_instance->m_ignoredKeysMutex);
                if (std::find(s_instance->m_ignoredKeys.begin(), s_instance->m_ignoredKeys.end(), pKey->vkCode) != s_instance->m_ignoredKeys.end()) {
                    isIgnored = true;
                }
            }

            if (!isIgnored && !(pKey->flags & LLKHF_INJECTED)) {
                s_instance->handleKeyboardEvent(wParam, pKey);
            }
        }
    }
    return CallNextHookEx(nullptr, nCode, wParam, lParam);
}

void HookManager::handleMouseEvent(WPARAM wParam, const MSLLHOOKSTRUCT* pMouse) {
    if (!m_settings.recordMouse) return;

    uint64_t currentMs = m_timer.getElapsedMs();
    uint32_t delay = static_cast<uint32_t>(currentMs - m_lastEventTimeMs);

    MacroEvent evt{};
    evt.timestampMs = currentMs;
    evt.delayMs = delay;
    evt.x = pMouse->pt.x;
    evt.y = pMouse->pt.y;

    bool recordThis = false;

    switch (wParam) {
        case WM_MOUSEMOVE: {
            if (!m_settings.recordMouseMoves) return;
            // Throttle rate
            if ((currentMs - m_lastMouseMoveTimeMs) < m_settings.mouseMoveIntervalMs) {
                return;
            }
            // Check distance threshold to filter out stationary mouse and sensor jitter
            int dx = std::abs(evt.x - m_lastRecordedX);
            int dy = std::abs(evt.y - m_lastRecordedY);
            if (dx < m_settings.mouseMoveThresholdPx && dy < m_settings.mouseMoveThresholdPx) {
                return;
            }

            evt.type = EventType::MouseMove;
            m_lastMouseMoveTimeMs = currentMs;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        }
        case WM_LBUTTONDOWN:
            evt.type = EventType::MouseDown;
            evt.button = MouseButton::Left;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        case WM_LBUTTONUP:
            evt.type = EventType::MouseUp;
            evt.button = MouseButton::Left;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        case WM_RBUTTONDOWN:
            evt.type = EventType::MouseDown;
            evt.button = MouseButton::Right;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        case WM_RBUTTONUP:
            evt.type = EventType::MouseUp;
            evt.button = MouseButton::Right;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        case WM_MBUTTONDOWN:
            evt.type = EventType::MouseDown;
            evt.button = MouseButton::Middle;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        case WM_MBUTTONUP:
            evt.type = EventType::MouseUp;
            evt.button = MouseButton::Middle;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        case WM_XBUTTONDOWN: {
            WORD xBtn = HIWORD(pMouse->mouseData);
            evt.type = EventType::MouseDown;
            evt.button = (xBtn == XBUTTON1) ? MouseButton::XButton1 : MouseButton::XButton2;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        }
        case WM_XBUTTONUP: {
            WORD xBtn = HIWORD(pMouse->mouseData);
            evt.type = EventType::MouseUp;
            evt.button = (xBtn == XBUTTON1) ? MouseButton::XButton1 : MouseButton::XButton2;
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        }
        case WM_MOUSEWHEEL: {
            evt.type = EventType::MouseWheel;
            evt.wheelDelta = GET_WHEEL_DELTA_WPARAM(pMouse->mouseData);
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        }
        case WM_MOUSEHWHEEL: {
            evt.type = EventType::MouseHWheel;
            evt.wheelDelta = GET_WHEEL_DELTA_WPARAM(pMouse->mouseData);
            m_lastRecordedX = evt.x;
            m_lastRecordedY = evt.y;
            recordThis = true;
            break;
        }
        default:
            break;
    }

    if (recordThis) {
        m_lastEventTimeMs = currentMs;
        {
            std::lock_guard<std::mutex> lock(m_eventMutex);
            m_events.push_back(evt);
        }
        if (m_eventCallback) {
            m_eventCallback(evt);
        }
    }
}

void HookManager::handleKeyboardEvent(WPARAM wParam, const KBDLLHOOKSTRUCT* pKey) {
    if (!m_settings.recordKeyboard) return;

    uint64_t currentMs = m_timer.getElapsedMs();
    uint32_t delay = static_cast<uint32_t>(currentMs - m_lastEventTimeMs);

    MacroEvent evt{};
    evt.timestampMs = currentMs;
    evt.delayMs = delay;
    evt.vkCode = pKey->vkCode;
    evt.scanCode = pKey->scanCode;
    evt.isExtendedKey = (pKey->flags & LLKHF_EXTENDED) != 0;

    bool recordThis = false;

    if (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN) {
        evt.type = EventType::KeyDown;
        recordThis = true;
    } else if (wParam == WM_KEYUP || wParam == WM_SYSKEYUP) {
        evt.type = EventType::KeyUp;
        recordThis = true;
    }

    if (recordThis) {
        m_lastEventTimeMs = currentMs;
        {
            std::lock_guard<std::mutex> lock(m_eventMutex);
            m_events.push_back(evt);
        }
        if (m_eventCallback) {
            m_eventCallback(evt);
        }
    }
}

} // namespace MacroK
